### ISSUE TITLE
feat: Introduced unocss module.

### ISSUE THREAD

**Issue by WuChenDi** [cdLab996/telegram-webapps-demo#8]
```sh
pnpm add -D @unocss/nuxt
```

Add `@unocss/nuxt` to your Nuxt config file:

```ts
// nuxt.config.ts
export default defineNuxtConfig({
  modules: [
    '@unocss/nuxt',
  ],
})
```

Create a `uno.config.ts` file:

```ts
// uno.config.ts
import { defineConfig } from 'unocss'

export default defineConfig({
  // ...UnoCSS options
})
```

**Comment by WuChenDi** [comment]
```bash
$ pnpm run generate

> nuxt-app@1.0.0 generate C:\wudi\github\cdLab996\telegram-webapps-demo
> nuxt generate

Nuxt 3.10.3 with Nitro 2.8.1                                                                11:33:05
ℹ Using Nitro server preset: static                                                        11:33:05
ℹ Building client...                                                                       11:33:10
ℹ vite v5.1.4 building for production...                                                   11:33:10

[11:33:12]  WARN  [plugin:vite:resolve] Module "crypto" has been externalized for browser compatibility, imported by "C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/telegram@2.19.20/node_modules/telegram/CryptoFile.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

node_modules/.pnpm/vconsole@3.15.1/node_modules/vconsole/dist/vconsole.min.js (10:75243) Use of eval in "node_modules/.pnpm/vconsole@3.15.1/node_modules/vconsole/dist/vconsole.min.js" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/.pnpm/vconsole@3.15.1/node_modules/vconsole/dist/vconsole.min.js (10:76655) Use of eval in "node_modules/.pnpm/vconsole@3.15.1/node_modules/vconsole/dist/vconsole.min.js" is strongly discouraged as it poses security risks and may cause issues with minification.
ℹ ✓ 184 modules transformed.                                                               11:33:14

 ERROR  x Build failed in 4.17s                                                             11:33:14


[11:33:14]  ERROR  Nuxt Build Error: [unocss:global:build:bundle] [unocss] does not found CSS placeholder in the generated chunks
This is likely an internal bug of unocss vite plugin

  This is likely an internal bug of unocss vite plugin
  at error (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
  at Object.error (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/es/shared/node-entry.js:18485:20)
  at Object.generateBundle (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/@unocss+vite@0.58.5_rollup@4.9.4_vite@5.1.4/node_modules/@unocss/vite/dist/index.mjs:590:16)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Bundle.generate (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/es/shared/node-entry.js:17037:9)
  at async /C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/es/shared/node-entry.js:19583:27
  at async catchUnfinishedHookActions (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/rollup@4.9.4/node_modules/rollup/dist/es/shared/node-entry.js:19014:16)
  at async Module.build (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/vite@5.1.4_sass@1.71.1/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:66934:22)
  at async buildClient (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/@nuxt+vite-builder@3.10.3_eslint@8.57.0_rollup@4.9.4_sass@1.71.1_typescript@5.3.3_vue-tsc@1.8.27_vue@3.4.20/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.DNatXv9H.mjs:601:5)
  at async bundle (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/@nuxt+vite-builder@3.10.3_eslint@8.57.0_rollup@4.9.4_sass@1.71.1_typescript@5.3.3_vue-tsc@1.8.27_vue@3.4.20/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.DNatXv9H.mjs:1525:3)
  at async bundle (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/nuxt@3.10.3_eslint@8.57.0_rollup@4.9.4_sass@1.71.1_typescript@5.3.3_vite@5.1.4_vue-tsc@1.8.27/node_modules/nuxt/dist/index.mjs:4896:5)
  at async Promise.all (index 1)
  at async build (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/nuxt@3.10.3_eslint@8.57.0_rollup@4.9.4_sass@1.71.1_typescript@5.3.3_vite@5.1.4_vue-tsc@1.8.27/node_modules/nuxt/dist/index.mjs:4771:5)
  at async Object.run (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/build.mjs:95:5)
  at async Object.run (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/generate.mjs:56:5)
  at async runCommand$1 (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/shared/nuxi.a9f3bca7.mjs:1648:16)
  at async runCommand$1 (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/shared/nuxi.a9f3bca7.mjs:1639:11)
  at async runMain$1 (/C:/wudi/github/cdLab996/telegram-webapps-demo/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/shared/nuxi.a9f3bca7.mjs:1777:7)

 ELIFECYCLE  Command failed with exit code 1.
```
